name: Tests
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: dev ${{ matrix.os }}, py-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # windows-latest, macOS-latest -> problem with MAGMA/CUDA 12.1
        os: [ ubuntu-latest ]
        python-version: [ "3.11", "3.12" ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: pre-commit/action@v3.0.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Run tests
        run: |
          coverage run -m unittest
          coverage xml
          coverage report -m

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-ci-gromo
          verbose: true
          token: ${{ secrets.CODECOV2_TOKEN }}
        # env:
        #   CODECOV_TOKEN: ${{ secrets.CODECOV2_TOKEN }}

      #  alternative if codecov/codecov-action fails
      # - shell: bash
      #   env:
      #     CODECOVSEC: ${{ secrets.CODECOV_TOKEN }}
      #   run: |
      #     curl -Os https://cli.codecov.io/latest/linux/codecov
      #     chmod +x codecov
      #     ./codecov --verbose upload-process --fail-on-error -n 'gh-actions'-${{ github.run_id }} -F ci -f coverage.xml -t "${CODECOVSEC}"
